CREATE OR ALTER VIEW vw_sales AS
SELECT
  o.ROW_ID,
  o.ORDER_ID,
  o.ORDER_DATE,
  o.SHIP_DATE,
  o.SHIP_MODE,
  o.SALES,
  o.QUANTITY,
  o.DISCOUNT,
  o.PROFIT,

  c.ID AS CUSTOMER_ID,
  c.NAME AS CUSTOMER_NAME,
  c.SEGMENT,
  c.CITY  AS CUSTOMER_CITY,
  c.STATE AS CUSTOMER_STATE,
  c.REGION AS CUSTOMER_REGION,

  p.ID AS PRODUCT_ID,
  p.NAME AS PRODUCT_NAME,
  p.CATEGORY,
  p.SUBCATEGORY,

  e.ID_EMPLOYEE AS EMPLOYEE_ID,
  e.NAME AS EMPLOYEE_NAME,
  e.REGION AS EMPLOYEE_REGION
FROM ORDERS o
JOIN CUSTOMER c ON o.CUSTOMER_ID = c.ID
JOIN PRODUCT  p ON o.PRODUCT_ID  = p.ID
JOIN EMPLOYEES e ON o.ID_EMPLOYEE = e.ID_EMPLOYEE;
